version: "3.8"
services:
  app:
    build: ./main
    links:
      - db
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "32000:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATA_BASE: 'employee'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      ##- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
